name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tox:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Store Cert & PK secrets
          env:
            CERT: ${{ secrets.TEST_CERTIFICATE }}
            PK: ${{ secrets.TEST_CERTIFICATE_PK }}
          run: |
            echo $CERT > src/configs/cert.pem
            echo $PK > src/configs/key.pem

        - name: Setup operator environment
          uses: charmed-kubernetes/actions-operator@main
          with:
            provider: microk8s
            channel: 1.29-strict/stable
            juju-channel: 3.4/stable
            lxd-channel: 5.20/stable

        - name: Run Tox
          run: |
            tox

        - name: Run integration tests
          run: |
            tox -e integration