name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: setup operator environment
          uses: charmed-kubernetes/actions-operator@main
          with:
            provider: microk8s
            channel: 1.29-strict/stable
            juju-channel: 3.4/stable
            lxd-channel: 5.20/stable
        - name: format
          run: |
            tox -e format
        - name: lint
          run: |
            tox -e lint
        - name: static
          run: |
            tox -e static
        - name: unit tests
          run: |
            tox -e unit
        - name: integration tests
          run: |
            tox -e integration